<?php

namespace Ebay\Sell\Account\V2\Api;

use Ebay\Sell\Account\V2\Model\RateTableDetails;
use Ebay\Sell\Account\V2\Model\RateTableUpdate;

class Table extends AbstractAPI
{
    /**
     * This method retrieves an existing rate table identified by the
     * <b>rate_table_id</b> path parameter.<br><br><b>getRateTable</b> currently
     * supports the retrieval of rate tables for the following eBay marketplace
     * IDs:<ul><li><code>EBAY_AU</code></li><li><code>EBAY_CA</code></li><li><code>EBAY_DE</code></li><li><code>EBAY_ES</code></li><li><code>EBAY_FR</code></li><li><code>EBAY_GB</code></li><li><code>EBAY_IT</code></li><li><code>EBAY_US</code></li></ul><span
     * class="tablenote"><b>Note:</b> To retrieve a list of all <b>rateTableId</b>
     * values, issue a <a
     * href="/api-docs/sell/account/resources/rate_table/methods/getRateTables "
     * target="_blank">getRateTables</a> call (part of <a
     * href="/api-docs/sell/account/static/overview.html " target="_blank">Account API
     * V1</a>,) with no <b>countryCode</b> query parameter specifed. This will return a
     * list of all shipping rate tables defined for each marketplace and their
     * corresponding <b>rateTableId</b> values.</span><br/><br/> A successful call
     * returns detailed information for the specified shipping rate table.
     *
     * @param string $rate_table_id The unique identifier for the shipping rate table.
     *                              This identifier is generated by eBay when a shipping rate table is first
     *                              created.<br/><br/><span class="tablenote"><strong>Note:</strong> To retrieve a
     *                              list of all <b>rateTableId</b> values, issue a <a
     *                              href="/api-docs/sell/account/resources/rate_table/methods/getRateTables"
     *                              target="_blank">getRateTables</a> call (part of <a
     *                              href="/api-docs/sell/account/static/overview.html " target="_blank">Account API
     *                              V1</a>,) with no <b>countryCode</b> query parameter specifed. This will return a
     *                              list of all shipping rate tables defined for each marketplace and their
     *                              corresponding <b>rateTableId</b> values.</span>
     *
     * @return RateTableDetails
     */
    public function get(string $rate_table_id): RateTableDetails
    {
        return $this->request(
        'getRateTable',
        'GET',
        "rate_table/$rate_table_id",
        null,
        [],
        []
        );
    }

    /**
     * This method allows sellers to update <b>shippingCost</b> and/or
     * <b>additionalCost</b> information for an existing shipping rate table identified
     * by the <b>rate_table_id</b> path parameter.<br/><br/><span
     * class="tablenote"><b>Note:</b> To retrieve a list of all <b>rateTableId</b>
     * values, issue a <a
     * href="/api-docs/sell/account/resources/rate_table/methods/getRateTables "
     * target="_blank">getRateTables</a> call (part of <a
     * href="/api-docs/sell/account/static/overview.html " target="_blank">Account API
     * V1</a>,) with no <b>countryCode</b> query parameter specifed. This will return a
     * list of all shipping rate tables and corresponding <b>rateTableId</b>
     * values.</span><br/><br/>A successful call returns an HTTP status code of <b>204
     * No Content</b>.
     *
     * @param string          $rate_table_id The unique identifier for the shipping rate table.
     *                                       This identifier is generated by eBay when a shipping rate table is first
     *                                       created.<br/><br/><span class="tablenote"><strong>Note:</strong> To retrieve a
     *                                       list of all <b>rateTableId</b> values, issue a <a
     *                                       href="/api-docs/sell/account/resources/rate_table/methods/getRateTables"
     *                                       target="_blank">getRateTables</a> call (part of <a
     *                                       href="/api-docs/sell/account/static/overview.html " target="_blank">Account API
     *                                       V1</a>,) with no <b>countryCode</b> query parameter specifed. This will return a
     *                                       list of all shipping rate tables defined for each marketplace and their
     *                                       corresponding <b>rateTableId</b> values.
     * @param RateTableUpdate $Model         request to update the shipping costs for the
     *                                       identified shipping rate table
     *
     * @return mixed
     */
    public function updateShippingCost(string $rate_table_id, RateTableUpdate $Model): mixed
    {
        return $this->request(
        'updateShippingCost',
        'POST',
        "rate_table/$rate_table_id/update_shipping_cost",
        $Model->getArrayCopy(),
        [],
        []
        );
    }
}
